import Head from 'next/head'
import { useState } from 'react'

export default function Dashboard() {

    const [viewProfile, setViewProfile] = useState(false)

    return (
        <>
            <Head>
                <title>PostcatAF - Home</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>

                <div className="flex h-screen overflow-hidden bg-white">
                    <div className="hidden md:flex md:flex-shrink-0">
                        <div className="flex flex-col w-64">
                            <div className="flex flex-col flex-grow pt-5 overflow-y-auto bg-white border-r">
                                <div className="flex flex-col flex-shrink-0 px-4">
                                    <a className="text-lg font-semibold tracking-tighter text-black focus:outline-none focus:ring px-4" href="/">
                                        <span className="inline-flex items-center gap-2">
                                            <svg className="w-5 h-5 mx-auto" viewBox="0 0 232 232" fill="none" xmlns="http://www.w3.org/2000/svg">
                                                <path d="M166.524 51.4683L116.367 101.625L65.5235 51.4683L116.367 0.62434L166.524 51.4683ZM231.11 116.054L180.953 166.898L130.796 116.054L180.953 65.8969L231.11 116.054ZM101.939 116.054L51.0948 166.898L0.250934 116.054L51.0948 65.8969L101.939 116.054ZM166.524 181.326L116.367 231.483L65.5235 181.326L116.367 130.482L166.524 181.326Z" fill="#0c0c0c"></path>
                                            </svg>

                                            PostcatAF
                                        </span>          </a>
                                    <button className="hidden rounded-lg focus:outline-none focus:shadow-outline">
                                        <svg fill="currentColor" viewBox="0 0 20 20" className="w-6 h-6">
                                            <path fill-rule="evenodd" d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM9 15a1 1 0 011-1h6a1 1 0 110 2h-6a1 1 0 01-1-1z" clip-rule="evenodd"></path>
                                            <path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path>
                                        </svg>
                                    </button>
                                </div>
                                <div className="flex flex-col flex-grow px-4 mt-5">
                                    <nav className="flex-1 space-y-1 bg-white">
                                        <p className="px-4 pt-4 text-xs font-semibold text-gray-400 uppercase">
                                            Analytics
                                        </p>
                                        <ul>
                                            <li>
                                                <a className="inline-flex items-center w-full px-4 py-2 mt-1 text-sm text-gray-500 transition duration-200 ease-in-out transform rounded-lg focus:shadow-outline hover:bg-gray-100 hover:scale-95 hover:text-blue-500" href="#">
                                                    <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-dashboard" width="20" height="20" viewBox="0 0 24 24" stroke-width="0.5" stroke="#000000" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                                        <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                                                        <circle cx="12" cy="13" r="2" />
                                                        <line x1="13.45" y1="11.55" x2="15.5" y2="9.5" />
                                                        <path d="M6.4 20a9 9 0 1 1 11.2 0z" />
                                                    </svg>
                                                    <span className="ml-4">
                                                        Dashboard
                                                    </span>
                                                </a>
                                            </li>
                                            <li>
                                                <a className="inline-flex items-center w-full px-4 py-2 mt-1 text-sm text-gray-500 transition duration-200 ease-in-out transform rounded-lg focus:shadow-outline hover:bg-gray-100 hover:scale-95 hover:text-blue-500" href="#">
                                                    <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-chart-line" width="20" height="20" viewBox="0 0 24 24" stroke-width="0.5" stroke="#000000" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                                        <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                                                        <line x1="4" y1="19" x2="20" y2="19" />
                                                        <polyline points="4 15 8 9 12 11 16 6 20 10" />
                                                    </svg>
                                                    <span className="ml-4">
                                                        Performance
                                                    </span>
                                                </a>
                                            </li>
                                        </ul>
                                        <p className="px-4 pt-4 text-xs font-semibold text-gray-400 uppercase">
                                            Content
                                        </p>
                                        <ul>
                                            <li>
                                                <a className="inline-flex items-center w-full px-4 py-2 mt-1 text-sm text-gray-500 transition duration-200 ease-in-out transform rounded-lg focus:shadow-outline hover:bg-gray-100 hover:scale-95 hover:text-blue-500" href="#">
                                                    <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-notebook" width="20" height="20" viewBox="0 0 24 24" stroke-width="0.5" stroke="#000000" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                                        <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                                                        <path d="M6 4h11a2 2 0 0 1 2 2v12a2 2 0 0 1 -2 2h-11a1 1 0 0 1 -1 -1v-14a1 1 0 0 1 1 -1m3 0v18" />
                                                        <line x1="13" y1="8" x2="15" y2="8" />
                                                        <line x1="13" y1="12" x2="15" y2="12" />
                                                    </svg>
                                                    <span className="ml-4">
                                                        Guides
                                                    </span>
                                                </a>
                                            </li>
                                            <li>
                                                <a className="inline-flex items-center w-full px-4 py-2 mt-1 text-sm text-gray-500 transition duration-200 ease-in-out transform rounded-lg focus:shadow-outline hover:bg-gray-100 hover:scale-95 hover:text-blue-500" href="#">
                                                    <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-refresh" width="20" height="20" viewBox="0 0 24 24" stroke-width="0.5" stroke="#000000" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                                        <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                                                        <path d="M20 11a8.1 8.1 0 0 0 -15.5 -2m-.5 -4v4h4" />
                                                        <path d="M4 13a8.1 8.1 0 0 0 15.5 2m.5 4v-4h-4" />
                                                    </svg>
                                                    <span className="ml-4">
                                                        Hotspots
                                                    </span>
                                                    <span className="inline-flex ml-auto items-center rounded-full bg-blue-50 px-2.5 py-0.5 text-xs font-medium text-blue-500">
                                                        25
                                                    </span>
                                                </a>
                                            </li>
                                            <li>
                                                <a className="inline-flex items-center w-full px-4 py-2 mt-1 text-sm text-gray-500 transition duration-200 ease-in-out transform rounded-lg focus:shadow-outline hover:bg-gray-100 hover:scale-95 hover:text-blue-500" href="#">
                                                    <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-clipboard-check" width="20" height="20" viewBox="0 0 24 24" stroke-width="0.5" stroke="#000000" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                                        <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                                                        <path d="M9 5h-2a2 2 0 0 0 -2 2v12a2 2 0 0 0 2 2h10a2 2 0 0 0 2 -2v-12a2 2 0 0 0 -2 -2h-2" />
                                                        <rect x="9" y="3" width="6" height="4" rx="2" />
                                                        <path d="M9 14l2 2l4 -4" />
                                                    </svg>
                                                    <span className="ml-4">
                                                        Checklist
                                                    </span>
                                                </a>
                                            </li>
                                            <li>
                                                <a className="inline-flex items-center w-full px-4 py-2 mt-1 text-sm text-gray-500 transition duration-200 ease-in-out transform rounded-lg focus:shadow-outline hover:bg-gray-100 hover:scale-95 hover:text-blue-500" href="#">
                                                    <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-heart" width="20" height="20" viewBox="0 0 24 24" stroke-width="0.5" stroke="#000000" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                                        <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                                                        <path d="M19.5 13.572l-7.5 7.428l-7.5 -7.428m0 0a5 5 0 1 1 7.5 -6.566a5 5 0 1 1 7.5 6.572" />
                                                    </svg>
                                                    <span className="ml-4">
                                                        TLD
                                                    </span>
                                                </a>
                                            </li>
                                        </ul>
                                        <p className="px-4 pt-4 text-xs font-semibold text-gray-400 uppercase">
                                            Customization
                                        </p>
                                        <ul>
                                            <li>
                                                <a className="inline-flex items-center w-full px-4 py-2 mt-1 text-sm text-gray-500 transition duration-200 ease-in-out transform rounded-lg focus:shadow-outline hover:bg-gray-100 hover:scale-95 hover:text-blue-500" href="#">
                                                    <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-archive" width="20" height="20" viewBox="0 0 24 24" stroke-width="0.5" stroke="#000000" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                                        <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                                                        <rect x="3" y="4" width="18" height="4" rx="2" />
                                                        <path d="M5 8v10a2 2 0 0 0 2 2h10a2 2 0 0 0 2 -2v-10" />
                                                        <line x1="10" y1="12" x2="14" y2="12" />
                                                    </svg>
                                                    <span className="ml-4">
                                                        Segments
                                                    </span>
                                                    <span className="inline-flex ml-auto items-center rounded-full bg-red-100 px-2.5 py-0.5 text-xs font-medium text-red-500">
                                                        25
                                                    </span>
                                                </a>
                                            </li>
                                        </ul>
                                    </nav>
                                </div>
                                <div className="flex flex-shrink-0 p-4 px-4 bg-gray-50">
                                    <div className="relative inline-flex items-center w-full" x-data="{ open: false }">
                                        <button onClick={() => setViewProfile(!viewProfile)} className="inline-flex items-center justify-between w-full px-4 py-3 text-lg font-medium text-center text-white transition duration-500 ease-in-out transform rounded-xl hover:bg-white focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500">
                                            <span>
                                                <span className="flex-shrink-0 block group">
                                                    <div className="flex items-center">
                                                        <div>
                                                            <img className="inline-block object-cover rounded-full h-9 w-9" src="https://images.unsplash.com/flagged/photo-1570612861542-284f4c12e75f?ixlib=rb-1.2.1&amp;ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&amp;auto=format&amp;fit=crop&amp;w=2070&amp;q=80" alt="" />
                                                        </div>
                                                        <div className="ml-3 text-left">
                                                            <p className="text-sm font-medium text-gray-500 group-hover:text-blue-500">
                                                                Ángel García
                                                            </p>
                                                            <p className="text-xs font-medium text-gray-500 group-hover:text-blue-500">
                                                                Developer
                                                            </p>
                                                        </div>
                                                    </div>
                                                </span>
                                            </span>
                                            <svg xmlns="http://www.w3.org/2000/svg" className={`inline w-5 h-5 ml-4 text-black transition-transform duration-500 transform ${viewProfile ? 'rotate-180' : 'rotate-0'}`} viewBox="0 0 20 20" fill="currentColor">
                                                <path fill-rule="evenodd" d="M14.707 12.707a1 1 0 01-1.414 0L10 9.414l-3.293 3.293a1 1 0 01-1.414-1.414l4-4a1 1 0 011.414 0l4 4a1 1 0 010 1.414z" clip-rule="evenodd"></path>
                                            </svg>
                                        </button>
                                        <div className={`absolute bottom-20 z-50 w-full mx-auto mt-2 origin-bottom-right bg-white rounded-xl transition-all ${viewProfile ? '' : 'hidden'}`}>
                                            <div className="px-2 py-2 bg-white rounded-lg shadow-lg ring-1 ring-black ring-opacity-5">
                                                <ul>
                                                    <li>
                                                        <a className="inline-flex items-center w-full px-4 py-2 mt-1 text-sm text-gray-500 transition duration-200 ease-in-out transform rounded-lg focus:shadow-outline hover:bg-gray-100 hover:scale-95 hover:text-blue-500" href="#">
                                                            <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-user" width="20" height="20" viewBox="0 0 24 24" stroke-width="0.5" stroke="#000000" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                                                <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                                                                <circle cx="12" cy="7" r="4" />
                                                                <path d="M6 21v-2a4 4 0 0 1 4 -4h4a4 4 0 0 1 4 4v2" />
                                                            </svg>
                                                            <span className="ml-4">
                                                                Account
                                                            </span>
                                                        </a>
                                                    </li>
                                                    <li>
                                                        <a className="inline-flex items-center w-full px-4 py-2 mt-1 text-sm text-gray-500 transition duration-200 ease-in-out transform rounded-lg focus:shadow-outline hover:bg-gray-100 hover:scale-95 hover:text-blue-500" href="#">
                                                            <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-user-circle" width="20" height="20" viewBox="0 0 24 24" stroke-width="0.5" stroke="#000000" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                                                <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                                                                <circle cx="12" cy="12" r="9" />
                                                                <circle cx="12" cy="10" r="3" />
                                                                <path d="M6.168 18.849a4 4 0 0 1 3.832 -2.849h4a4 4 0 0 1 3.834 2.855" />
                                                            </svg>
                                                            <span className="ml-4">
                                                                Profile
                                                            </span>
                                                        </a>
                                                    </li>
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div className="flex flex-col flex-1 w-0 overflow-hidden">
                        <main className="relative flex-1 overflow-y-auto focus:outline-none">
                            <div className="py-6">
                                <div className="px-4 mx-auto 2xl:max-w-7xl sm:px-6 md:px-8">
                                    <div className="py-4">
                                        <div className="h-full border border-gray-200 border-dashed rounded-lg">
                                            <div className='w-full py-4 px-6 grid grid-cols-3'>
                                                <h1 className='font-semibold text-2xl'>Chat Grupal</h1>
                                                <div className="relative inline-flex items-center w-full" x-data="{ open: false }">
                                                    <div className="flex flex-col w-full">
                                                        <div className="relative">
                                                            <input type="text" className="w-full h-10 pl-3 pr-10 text-base placeholder-gray-600 border rounded-lg focus:shadow-outline" placeholder="Search" />
                                                            <div className="absolute inset-y-0 right-0 flex items-center pr-2 pointer-events-none">
                                                                <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-search" width="20" height="20" viewBox="0 0 24 24" stroke-width="0.5" stroke="#000000" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                                                    <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                                                                    <circle cx="10" cy="10" r="7" />
                                                                    <line x1="21" y1="21" x2="15" y2="15" />
                                                                </svg>

                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>

                                                <div className='flex justify-end'>
                                                    <button type="button" class="inline-flex items-center justify-center px-4 py-2 text-center text-black duration-200 bg-white border-2 border-black hover:bg-transparent hover:border-black rounded-xl hover:text-black focus:outline-none focus-visible:outline-black focus-visible:ring-black">
                                                        <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-notebook" width="20" height="20" viewBox="0 0 24 24" stroke-width="1.5" stroke="#000000" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                                            <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                                                            <path d="M6 4h11a2 2 0 0 1 2 2v12a2 2 0 0 1 -2 2h-11a1 1 0 0 1 -1 -1v-14a1 1 0 0 1 1 -1m3 0v18" />
                                                            <line x1="13" y1="8" x2="15" y2="8" />
                                                            <line x1="13" y1="12" x2="15" y2="12" />
                                                        </svg>
                                                    </button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>


                                    <div className="py-4">
                                        <div className="relative h-[45rem] border border-gray-200 border-dashed rounded-lg py-4 px-6">
                                            <div className='h-full'>
                                                <div className='flex'>
                                                    <div className='flex-shrink-0'>
                                                        <img className='h-10 w-10 rounded-full' src="https://jvngarcia.com/wp-content/uploads/2021/01/community-group.png" alt="" />
                                                    </div>
                                                    <div className='ml-4'>
                                                        <div className='flex items-center'>
                                                            <h3 className='text-sm font-medium text-gray-900'>
                                                                Juan Garcia
                                                            </h3>
                                                            <span className='ml-2 flex-shrink-0 inline-block px-2 py-0.5 text-green-800 text-xs font-medium bg-green-100 rounded-full'>
                                                                Online
                                                            </span>
                                                        </div>
                                                        <div className='mt-1 bg-gray-100 px-8 py-6 rounded-b-2xl rounded-tr-2xl'>
                                                            <p className='text-sm text-gray-500'>
                                                                Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.
                                                                Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.
                                                                Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.
                                                                Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.
                                                                Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.
                                                                Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.
                                                            </p>
                                                        </div>
                                                    </div>
                                                </div>


                                                <div className='flex mt-8 flex-row-reverse'>
                                                    <div className='flex-shrink-0'>
                                                        <img className='h-10 w-10 rounded-full' src="https://jvngarcia.com/wp-content/uploads/2021/01/community-group.png" alt="" />
                                                    </div>
                                                    <div className='mr-4'>
                                                        <div className='flex items-center justify-end'>
                                                            <h3 className='text-sm font-medium text-gray-900'>
                                                                Juan Garcia
                                                            </h3>
                                                            <span className='ml-2 flex-shrink-0 inline-block px-2 py-0.5 text-green-800 text-xs font-medium bg-green-100 rounded-full'>
                                                                Online
                                                            </span>
                                                        </div>
                                                        <div className='mt-2 bg-gray-50 px-8 py-6 rounded-b-2xl rounded-tl-2xl'>
                                                            <p className='text-sm text-gray-500 text-right'>
                                                                Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.
                                                                asda
                                                            </p>
                                                            <p className='text-sm text-gray-500 text-right'>
                                                                Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.
                                                                Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.
                                                                Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.
                                                                asdaasda a
                                                            </p>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>


                                            <div className='absolute bottom-0 left-0 bg-gray-50 w-full py-5 px-6 flex'>
                                                <input type="text" className="w-full h-10 pl-3 pr-10 text-base placeholder-gray-300 border rounded-lg focus:shadow-outline" placeholder="Hi!, how are you?" />
                                                <button className='ml-2 bg-blue-100 hover:bg-blue-200 px-4 border-blue-300 border rounded-lg transition-all'>
                                                    <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-send" width="20" height="20" viewBox="0 0 24 24" stroke-width="1" stroke="#1e3a8a" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                                        <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                                                        <line x1="10" y1="14" x2="21" y2="3" />
                                                        <path d="M21 3l-6.5 18a0.55 .55 0 0 1 -1 0l-3.5 -7l-7 -3.5a0.55 .55 0 0 1 0 -1l18 -6.5" />
                                                    </svg>
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </main>
                    </div>
                </div>
            </main>
        </>
    )
}